### PR TITLE
updated map link in footer. added target blank so users don't get tak…

### PR DESCRIPTION
**Pull request by writingbymatt**
updated map link in footer. added target blank so users don't get taken away from the omnicommons site, as well as replaced the map link with the google map so that users can easily get directions to the commons.

I know this is a small change. I'm learning to fork github projects and contribute to projects, which is why I'm starting small. :)

### CODE REVIEW

**Comment by yardenac** [comment]
A Google link sounds good, but this also removes the link to our Oakland Wiki page. It would be nice to still link to that somewhere. Any ideas?

**Comment by writingbymatt** [comment]
That's true. We could even add a link to the wiki in the nav

_Matt Hunt_
(510)-301-4197
@WritingByMatt http://twitter.com/writingbymatt

**Comment by yardenac** [comment]
That could work! Do you want to add that to your PR?

**Comment by writingbymatt** [comment]
sure!

_Matt Hunt_
(510)-301-4197
@WritingByMatt http://twitter.com/writingbymatt

**Comment by writingbymatt** [comment]
Just got home and looked at fixing this. THere is actually already a nav 
item to the wiki that omni is using, separate of the oakland wiki. I'll 
have to take a second look at how to build them both in.

_Matt Hunt_
(510)-301-4197
@WritingByMatt http://twitter.com/writingbymatt

**Comment by yardenac** [comment]
I just manually merged these at 73fcbebc and 06f6c218

**Pull request closed without merging**
